# -*- coding: utf-8 -*-
"""Part5_Geoparsing_and_Mapping.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mS0RAq5Mj6zAdZioZK4bW5DNemqtWGxI

# Geoparsing & Mapping of Fire Events in Greece based on X posts Script


**Description:**

This script implements the final stage of the pipeline: the geospatial analysis and the visualiation.
It takes the classified (Fire-related) tweets and performs Named Entity Recognition (NER) to extract locations,
followed by advanced Toponym Disambiguation and geocoding using OpenStreetMap (OSM) and its Nominatim API. Finally, it clusters the validated
events based on the proximity and generates an interactive spatiotemporal map.

**Methodology & Key Features:**

1.  **Entity Extraction:** Uses the 'gr-nlp-toolkit' to extract LOC, GPE, and FAC entities from the light-cleaned text format.
2.  **Spatiotemporal Memory:** Implements a 5-hour rolling memory of active fires to instantly anchor newly reported locations and eliminate spatial hijacking.
3.  **Document Context Disambiguation:** Dynamically anchors ambiguous toponyms using proximity to known events by calculating the centroid distance.
4.  **Spatial Clustering:** Utilizes the DBSCAN algorithm to group individual incident reports into unified operational fire clusters.
5.  **Interactive Visualization:** Generates a dynamic Folium map with a Time Slider and detailed HTML popups for each fire event.

**References:**

*GR-NLP Toolkit: https://github.com/nlpaueb/gr-nlp-toolkit*

*Nominatim API (OSM): https://nominatim.org/release-docs/develop/api/Search/*

*DBSCAN (scikit-learn): https://scikit-learn.org/stable/modules/generated/sklearn.cluster.DBSCAN.html*
"""

# LIBRARIES

### The following need to be deleted in the .py file for the simulation
### START
#!pip install gr-nlp-toolkit geopy folium scikit-learn pandas tqdm -q
### END

import pandas as pd
import numpy as np
import time
import folium
import io
import difflib
import unicodedata
from collections import Counter
from functools import lru_cache
from google.colab import files
from geopy.geocoders import Nominatim
from geopy.distance import geodesic
from itertools import combinations
from sklearn.cluster import DBSCAN
from gr_nlp_toolkit import Pipeline
from folium.plugins import TimestampedGeoJson
from tqdm import tqdm
from datetime import timedelta

tqdm.pandas()

print("Initializing GR-NLP-Toolkit Pipeline...")
nlp_pipeline = Pipeline("ner")
geolocator = Nominatim(user_agent="fire_event_geoparser")

# ================= CONFIGURATION =================
# Dates used (!) ONLY (!) for mapping (Format: 'YYYY-MM-DD') -> if in comment (#) = None
START_DATE = '2025-08-27'
END_DATE = '2025-08-29'

# Disambiguation Parameters
DISAMBIGUATION_THRESHOLD_KM = 40.0
STRICT_THRESHOLD_KM = 20.0
FUZZY_MATCH_THRESHOLD = 0.80 # Text similarity percentage for intra-tweet deduplication

# Spatiotemporal memory from recent fire events to disambiguate new event mentions
TIME_WINDOW_HOURS = 5.0 # Remembers locations of fire events from the past 5 hours

# Clustering Parameters
CLUSTERING_EPSILON_KM = 15.0 # Maximum distance between two points to be considered neighbors
CLUSTERING_MIN_SAMPLES = 2 # Minimum number of samples to be considered as a cluster

# Map View (Center: Greece)
MAP_CENTER_LAT = 39.0742
MAP_CENTER_LON = 21.8243
MAP_ZOOM = 7

# --- Evaluation Parameters ---
EVALUATION_DISTANCE_KM = 10.0 # Distance (in km) limit considered as succesful geocoding

# Fade Out Effect Parameters (for Folium's Time Slider)
FADE_STEPS = 6                  # Number of fade outs (echoes) -> 6 steps of 30 min = 3hr total
TIME_INTERVAL_MINS = 30         # Time interval of each step (in min) -> brightness changes every 30 min
INITIAL_OPACITY = 0.9           # Initial - max brightness of the fire event

# Common words blocked because of frequent misclassification as locations
MACRO_LOCATIONS = {
    'ελλαδα', 'ελλαδας', 'ελλαδος', 'ελλας', 'ελλάδα', 'ελλάδας', 'ελλάδος', 'ελλάς',
    'κυπρος', 'κυπρου', 'κυπρο', 'κύπρος', 'κύπρου', 'κύπρο', 'greece', 'cyprus', 'hellas'
}

# ================= HELPER FUNCTIONS =================

def is_fuzzy_match(s1, s2, threshold=FUZZY_MATCH_THRESHOLD):
    """
    Checks if two strings are highly similar using fuzzy logic.
    Useful for matching different declensions of Greek words (e.g., 'Κομοτηνή' vs 'Κομοτηνής').
    """
    return difflib.SequenceMatcher(None, s1.lower(), s2.lower()).ratio() >= threshold

def get_min_dist(coord, memory_list):
    """
    Calculates the minimum distance (in kilometers) between a given coordinate
    and all active fire locations currently stored in the spatiotemporal memory.
    """
    if not memory_list: return float('inf')
    return min(geodesic((coord['lat'], coord['lon']), (m['coords']['lat'], m['coords']['lon'])).km for m in memory_list)

def get_fallback(candidates):
    """
    Returns the candidate location with the highest 'importance' score from the Nominatim API.
    Used as a fallback when spatial context is insufficient for disambiguation.
    """
    return max(candidates, key=lambda x: x['importance'])

def normalize_text(text):
    """
    Removes accents and converts Greek text to lowercase for fair string matching.
    Used for both NER extraction results and Ground Truth comparison.
    """
    if pd.isna(text) or not isinstance(text, str):
        return ""
    text = unicodedata.normalize('NFD', text)
    text = ''.join(char for char in text if unicodedata.category(char) != 'Mn')
    return text.lower().strip()

# ================= CORE FUNCTIONS =================

# =============================================================================
# DATASET ALIGNMENT & ROW MANAGEMENT (FIXED FOR GROUND TRUTH DATASET)
# =============================================================================

def align_geoparsed_results(geoparsed_df, ground_truth_df):
    """
    Synchronizes predictions with Ground Truth dataset using only the Tweet_ID.
    """
    flattened_data = []

    # Cleaning
    geoparsed_df['Tweet_ID_clean'] = geoparsed_df['Tweet_ID'].astype(str).str.replace(r'\.0$', '', regex=True).str.strip()
    ground_truth_df['Tweet_ID_clean'] = ground_truth_df['Tweet_ID'].astype(str).str.replace(r'\.0$', '', regex=True).str.strip()

    for _, gt_row in ground_truth_df.iterrows():
        t_id = gt_row['Tweet_ID_clean']
        gt_toponym = normalize_text(gt_row.get('Actual_Toponym', ''))

        base_row = {
            'Tweet_ID': gt_row['Tweet_ID'],
            'Raw_Text': gt_row.get('Raw_Text', ''),
            'Actual_Toponym': gt_row.get('Actual_Toponym', ''),
            'Actual_Lat': gt_row.get('Actual_Lat', None),
            'Actual_Lon': gt_row.get('Actual_Lon', None),
            'Notes': gt_row.get('Notes', ''),
            'NER_Extracted': 'MISSING',
            'Geocoded_As': 'NONE',
            'Predicted_Lat': None,
            'Predicted_Lon': None
        }

        # We find the corresponding tweet in the geoparsing results
        pred_match = geoparsed_df[geoparsed_df['Tweet_ID_clean'] == t_id]

        if not pred_match.empty:
            p_row = pred_match.iloc[0]
            ner_locs = p_row.get('Extracted_Locations', [])
            geo_coords = p_row.get('Coordinates', [])

            if isinstance(ner_locs, list):
                for loc in ner_locs:
                    pred_toponym = normalize_text(loc.get('name', ''))

                    if pred_toponym != "" and gt_toponym != "" and (pred_toponym in gt_toponym or gt_toponym in pred_toponym):
                        base_row['NER_Extracted'] = loc.get('name', '')

                        if isinstance(geo_coords, list):
                            matching_coord = next((c for c in geo_coords if c.get('original_name') == loc.get('name')), None)

                            if matching_coord:
                                base_row['Geocoded_As'] = matching_coord.get('name', '')
                                base_row['Predicted_Lat'] = matching_coord.get('lat', None)
                                base_row['Predicted_Lon'] = matching_coord.get('lon', None)

                        break

        flattened_data.append(base_row)

    return pd.DataFrame(flattened_data)

# =============================================================================
# EVALUATION METRICS (From geoparsing_evaluation script)
# =============================================================================

def evaluate_geoparsing(eval_df, distance_threshold_km=EVALUATION_DISTANCE_KM):
    """
    Calculates NER extraction accuracy and Geocoding spatial accuracy.
    Assumes the input dataframe is the flattened version containing both
    predictions and ground truth.
    """
    print("\n--- STARTING EVALUATION ---")

    total_targets = len(eval_df)
    if total_targets == 0:
        print("[WARNING] No data available for evaluation.")
        return eval_df

    # 1. NER Evaluation (Strict & Partial Matching)
    ner_strict_correct = 0
    ner_partial_correct = 0

    for _, row in eval_df.iterrows():
        extracted = normalize_text(row.get('NER_Extracted', ''))
        actual = normalize_text(row.get('Actual_Toponym', ''))

        if extracted == 'none' and actual == '':
            # True Negative: Model correctly identified no location
            ner_strict_correct += 1
            ner_partial_correct += 1
        elif extracted != '' and actual != '':
            if extracted == actual:
                # Exact match
                ner_strict_correct += 1
                ner_partial_correct += 1
            elif extracted in actual or actual in extracted:
                # Partial match (e.g., 'Αθήνα' in 'Δήμος Αθηναίων')
                ner_partial_correct += 1

    ner_strict_acc = (ner_strict_correct / total_targets) * 100 if total_targets > 0 else 0
    ner_partial_acc = (ner_partial_correct / total_targets) * 100 if total_targets > 0 else 0

    print(f"\n[1] NER PERFORMANCE")
    print(f"Total Entities Evaluated     : {total_targets}")
    print(f"--------------------------------------------------")
    print(f"Strictly Correct Entities    : {ner_strict_correct}")
    print(f"Strict Accuracy              : {ner_strict_acc:.2f}%")
    print(f"--------------------------------------------------")
    print(f"Partially Correct Entities   : {ner_partial_correct}")
    print(f"Partial/Operational Accuracy : {ner_partial_acc:.2f}%") # Indicates how often the model correctly identified the geographic entity
    print(f"--------------------------------------------------")

    # 2. Geocoding Evaluation (Spatial Accuracy)
    distances = []
    correct_within_threshold = 0
    valid_geo_targets = 0

    for _, row in eval_df.iterrows():
        # Only evaluate geocoding if there is an actual location in Ground Truth
        if pd.notna(row.get('Actual_Lat')) and str(row.get('Actual_Lat')).strip() != '':
            valid_geo_targets += 1

            pred_lat = row.get('Predicted_Lat')
            pred_lon = row.get('Predicted_Lon')
            act_lat = row.get('Actual_Lat')
            act_lon = row.get('Actual_Lon')

            # --- Calculation only if coordinates exist ---
            if pd.notna(pred_lat) and pd.notna(pred_lon):
                try:
                    dist = geodesic((float(pred_lat), float(pred_lon)), (float(act_lat), float(act_lon))).km

                    distances.append(dist)
                    if dist <= distance_threshold_km:
                        correct_within_threshold += 1

                except (ValueError, TypeError) as e:
                    print(f"[WARNING] Could not calculate distance for Tweet_ID {row.get('Tweet_ID')}: {e}")
                    continue

    if valid_geo_targets > 0:
        geo_accuracy = (correct_within_threshold / valid_geo_targets) * 100

        mean_error = np.nanmean(distances) if distances else 0
        median_error = np.nanmedian(distances) if distances else 0

        print(f"\n[2] GEOCODING PERFORMANCE")
        print(f"Total Valid Target Coordinates : {valid_geo_targets}")
        print(f"Geocoded within {distance_threshold_km}km       : {correct_within_threshold}")
        print(f"Operational Accuracy           : {geo_accuracy:.2f}%") # Indicates the percentage of cases where the system can direct emergency services to the correct broader area
        print(f"Mean Distance Error            : {mean_error:.2f} km")
        print(f"Median Distance Error          : {median_error:.2f} km")
    else:
        print(f"\n[2] GEOCODING PERFORMANCE: No valid coordinates to evaluate.")

    print("==================================================\n")

    return eval_df

@lru_cache(maxsize=1024)
def get_candidates_cached(loc_name):
    """
    Fetches geographic coordinates from the Nominatim API for a given location name.
    Implements API rate-limiting, caching (to avoid redundant calls), and 'Highway Removal'
    (ignoring streets/roads) to focus on wider geographic areas relevant to wildfires.
    """
    try:
        time.sleep(1.1) # Respect Nominatim API usage policy (1 request/sec)
        results = geolocator.geocode(loc_name, country_codes=['gr', 'cy'], exactly_one=False, limit=15, timeout=10) # We add Cyprus

        if not results: return []

        valid_candidates = []
        for res in results:
            raw = res.raw
            # Heuristic: Ignore streets/highways as wildfires usually cover broader areas
            if raw.get('class') == 'highway': continue

            # Heuristic: Ignore Embassies & Consulates
            if raw.get('type') in ['embassy', 'consulate']: continue

            valid_candidates.append({
                'lat': res.latitude, 'lon': res.longitude,
                'name': res.address.split(',')[0],
                'osm_class': raw.get('class', 'unknown'),
                'osm_type': raw.get('type', 'unknown'),
                'importance': raw.get('importance', 0.0)
            })
        return valid_candidates
    except Exception as e:
        print(f"  [API Error] '{loc_name}': {e}")
        time.sleep(2)
        return []

def extract_locations_smart(text):
    """
    Extracts Location Entities (GPE, LOC, FAC) using the GR-NLP toolkit.
    Includes hashtag symbol removal (to prevent NER blindness), macro-location filtering,
    and intra-tweet fuzzy deduplication (merging variations of the same name within one tweet).
    """
    if not isinstance(text, str): return []

    # Remove hashtags before NER processing (to be deleted after cleaning update)
    doc = nlp_pipeline(text.replace('#', ''))

    raw_locs = {}
    curr_loc, curr_tag = [], ""

    # Append None to ensure the buffer flushes on the final iteration
    for token in list(doc.tokens) + [None]:
        if token and token.ner and token.ner.endswith(("LOC", "GPE", "FAC")):
            curr_loc.append(token.text)
            curr_tag = token.ner.split('-')[-1]
        elif curr_loc:
            loc_str = " ".join(curr_loc).strip()
            if len(loc_str) > 2 and loc_str.lower() not in MACRO_LOCATIONS:
                raw_locs[loc_str] = curr_tag
            curr_loc, curr_tag = [], ""

    # Intra-tweet Fuzzy Deduplication (e.g., merge 'Αθήνα' and 'Αθήνας' if found in the same tweet)
    unique_locs = []
    for name, tag in raw_locs.items():
        if not any(is_fuzzy_match(name, u['name']) for u in unique_locs):
            unique_locs.append({'name': name, 'ner_label': tag})

    return unique_locs

def resolve_coordinates(row):
    global spatiotemporal_memory
    loc_list, tweet_time = row['Extracted_Locations'], row['Date']

    if not loc_list or pd.isnull(tweet_time): return []

    spatiotemporal_memory = [m for m in spatiotemporal_memory if (tweet_time - m['time']).total_seconds() <= TIME_WINDOW_HOURS * 3600]
    final_coords, unresolved_locs = [], []

    # 2. Pre-check: Memory location
    for loc in loc_list:
        match = next((m for m in spatiotemporal_memory if is_fuzzy_match(loc['name'], m['loc_name'])), None)
        if match:
            c_copy = match['coords'].copy()
            c_copy['ner_label'] = loc['ner_label']
            c_copy['original_name'] = loc['name']
            final_coords.append(c_copy)
            match['time'] = tweet_time
        else:
            unresolved_locs.append(loc)

    if not unresolved_locs: return final_coords

    cands_dict = {loc['name']: get_candidates_cached(loc['name']) for loc in unresolved_locs if get_candidates_cached(loc['name'])}
    ner_dict = {loc['name']: loc['ner_label'] for loc in unresolved_locs}
    locs_found = list(cands_dict.keys())

    if not locs_found: return final_coords

    # CASE A: Single location found
    if len(locs_found) == 1:
        loc_name = locs_found[0]
        cands = cands_dict[loc_name]

        best_cand = min(cands, key=lambda c: get_min_dist(c, spatiotemporal_memory), default=None)
        min_dist = get_min_dist(best_cand, spatiotemporal_memory) if best_cand else float('inf')

        is_valid = best_cand and ((cands.index(best_cand) == 0 and min_dist < DISAMBIGUATION_THRESHOLD_KM) or (cands.index(best_cand) > 0 and min_dist < STRICT_THRESHOLD_KM))

        chosen_coord = best_cand.copy() if is_valid else get_fallback(cands).copy()
        chosen_coord['ner_label'] = ner_dict[loc_name]
        chosen_coord['original_name'] = loc_name

        final_coords.append(chosen_coord)
        spatiotemporal_memory.append({'loc_name': loc_name, 'coords': chosen_coord, 'time': tweet_time})

    # CASE B: Multiple locations found
    else:
        resolved_dict = {}
        if spatiotemporal_memory:
            for loc in locs_found:
                best_cand = min(cands_dict[loc], key=lambda c: get_min_dist(c, spatiotemporal_memory), default=None)
                if best_cand and get_min_dist(best_cand, spatiotemporal_memory) < DISAMBIGUATION_THRESHOLD_KM:
                    c_copy = best_cand.copy()
                    c_copy['ner_label'] = ner_dict[loc]
                    c_copy['original_name'] = loc
                    resolved_dict[loc] = c_copy

        if resolved_dict:
            final_coords.extend(resolved_dict.values())
            anchors = list(resolved_dict.values())
        else:
            best_pair = None
            min_dist = float('inf')
            # If multiple unknown locations are extracted, we compute the distance between all pairs
            # to find the tightest spatial cluster, assuming they refer to the same incident.
            for l1, l2 in combinations(locs_found, 2):
                for c1 in cands_dict[l1]:
                    for c2 in cands_dict[l2]:
                        dist = geodesic((c1['lat'], c1['lon']), (c2['lat'], c2['lon'])).km
                        if dist < min_dist:
                            min_dist, best_pair = dist, {l1: c1, l2: c2}

            if best_pair and min_dist < DISAMBIGUATION_THRESHOLD_KM:
                for l_name, c in best_pair.items():
                    c_copy = c.copy()
                    c_copy['ner_label'] = ner_dict[l_name]
                    c_copy['original_name'] = l_name
                    final_coords.append(c_copy)
                    spatiotemporal_memory.append({'loc_name': l_name, 'coords': c_copy, 'time': tweet_time})
                anchors = list(final_coords[-len(best_pair):])
            else:
                for loc in locs_found:
                    best_c = get_fallback(cands_dict[loc]).copy()
                    best_c['ner_label'] = ner_dict[loc]
                    best_c['original_name'] = loc
                    final_coords.append(best_c)
                    spatiotemporal_memory.append({'loc_name': loc, 'coords': best_c, 'time': tweet_time})
                return final_coords

        centroid = (np.mean([c['lat'] for c in anchors]), np.mean([c['lon'] for c in anchors]))
        for loc in locs_found:
            if loc not in [a.get('original_name') for a in anchors]:
                best_c = min(cands_dict[loc], key=lambda c: geodesic((c['lat'], c['lon']), centroid).km).copy()
                if geodesic((best_c['lat'], best_c['lon']), centroid).km < DISAMBIGUATION_THRESHOLD_KM:
                    best_c['ner_label'] = ner_dict[loc]
                    best_c['original_name'] = loc
                    final_coords.append(best_c)
                    spatiotemporal_memory.append({'loc_name': loc, 'coords': best_c, 'time': tweet_time})

    return final_coords

# =============================================================================
# MAIN MAPPING PIPELINE (FOR SIMULATION & STANDALONE USE)
# =============================================================================

def run_mapping(df, target_label_col='Predicted Label', limit=None, start_date=None, end_date=None):
    """
    Processes the classified dataframe to extract locations, resolve coordinates,
    cluster events, and generate an interactive spatiotemporal map.
    """
    global spatiotemporal_memory
    # Reset spatiotemporal memory for each unique pipeline execution
    spatiotemporal_memory = []

    print("\n--- Step 1: Data Filtering and Preparation ---")

    # Safe data filtering (converts "1", "1.0" and 1 into the same number)
    def safe_filter(dataframe, col_name):

        str_col = dataframe[col_name].astype(str).str.lower().str.strip()

        # Handles potential datatype inconsistencies from upstream modules (e.g., bool, int, string representations of floats)
        valid_fire_labels = ['1', '1.0']
        #valid_fire_labels = ['1', '1.0', 'true', 'fire', 'yes', 'y']

        filtered_df = dataframe[str_col.isin(valid_fire_labels)].copy()

        if filtered_df.empty:
            numeric_col = pd.to_numeric(dataframe[col_name], errors='coerce')
            return dataframe[numeric_col >= 0.5].copy()

        return filtered_df

    if 'Predicted Label' in df.columns:
        print(f"[INFO] Simulation Mode. Values in column 'Predicted Label': {df['Predicted Label'].unique()}")
        fire_df = safe_filter(df, 'Predicted Label')

    elif 'is_fire' in df.columns:
        print(f"[INFO] Standalone Mode. Values in column 'is_fire': {df['is_fire'].unique()}")
        fire_df = safe_filter(df, 'is_fire')

    elif target_label_col in df.columns:
        print(f"[INFO] Fallback Mode. Values in column '{target_label_col}': {df[target_label_col].unique()}")
        fire_df = safe_filter(df, target_label_col)

    else:
        print("[WARNING] Predictions column not found. Continuing with all the data...")
        fire_df = df.copy()

    if limit is not None:
        fire_df = fire_df.head(limit)

    print(f"Total active fire tweets to geoparse: {len(fire_df)}")

    if fire_df.empty:
        print("[ERROR] No fire-related data found to map. Termination process.")
        return None

    # Convert 'Date' column to datetime objects using the specific Twitter/X format
    # This is crucial for the spatiotemporal disambiguation and time-slider functionality
    #fire_df['Date'] = pd.to_datetime(fire_df['Date'], format='%a %b %d %H:%M:%S %z %Y', utc=True, errors='coerce').sort_values()

    # Convert 'Date' column to datetime objects
    fire_df['Date'] = pd.to_datetime(fire_df['Date'], format='%a %b %d %H:%M:%S %z %Y', utc=True, errors='coerce')
    # Sort the entire dataframe chronologically so the spatiotemporal memory works correctly
    fire_df = fire_df.sort_values(by='Date').reset_index(drop=True)

    print("\n--- Step 2: Named Entity Recognition (NER) ---")
    # Extract location entities (GPE, LOC, FAC) using the custom smart extraction function
    fire_df['Extracted_Locations'] = fire_df['Light Cleaned Text'].progress_apply(extract_locations_smart)

    print("\n--- Step 3: Geocoding & Toponym Disambiguation ---")
    # Resolve ambiguous toponyms using spatiotemporal memory and document context
    coords_list = [resolve_coordinates(row) for _, row in tqdm(fire_df.iterrows(), total=len(fire_df), desc="Geocoding")]
    fire_df['Coordinates'] = coords_list

    # Save Geoparsing CSV before Mapping
    fire_df.to_csv('fire_events_geoparsed.csv', index=False)
    print("\n[INFO] Geoparsed dataset securely saved as 'fire_events_geoparsed.csv'")

    print("\n--- Step 4: Clustering & Visualization ---")
    flat_points, meta_info = [], []

    # ---------------------------------------------------------
    # Map Filtering
    # ---------------------------------------------------------
    map_df = fire_df.copy()

    if start_date and end_date:
        try:
            start_dt = pd.to_datetime(start_date, utc=True)
            end_dt = pd.to_datetime(end_date, utc=True) + pd.Timedelta(days=1, seconds=-1)
            mask = (map_df['Date'] >= start_dt) & (map_df['Date'] <= end_dt)
            map_df = map_df.loc[mask]
            print(f"[INFO] Filter applied for mapping: {start_date} to {end_date}.")
            print(f"       Tweets mapped (out of {len(fire_df)} total): {len(map_df)}")
        except Exception as e:
            print(f"[WARNING] Invalid date format in configuration. Mapping all data. Error: {e}")

    if map_df.empty:
        print("[WARNING] No events found in the specified dates. The map will be empty.")

    # 1. Initial collection of map points and RAW predictions
    for _, row in tqdm(map_df.iterrows(), total=len(map_df), desc="Extracting Map Points"):
        if isinstance(row['Coordinates'], list):
            f_pred = row.get('is_wildland_pred', row.get('is_wildland', 0))
            u_pred = row.get('is_urban_pred', row.get('is_urban', 0))

            for c in row['Coordinates']:
                flat_points.append([c['lat'], c['lon']])
                time_str = row['Date'].strftime('%Y-%m-%d %H:%M:%S') if pd.notnull(row.get('Date')) else "Unknown Date"

                # Save raw predictions to meta_info
                meta_info.append({
                    'loc_name': c['name'],
                    'text': row['Light Cleaned Text'],
                    'time': time_str,
                    'f_pred': f_pred,
                    'u_pred': u_pred
                })

    if not flat_points:
        print("No valid coordinates resolved for mapping.")
        return fire_df

    # 2. --- SPATIAL CLUSTERING (DBSCAN) ---
    CLUSTERING_EPSILON_KM = 15.0
    CLUSTERING_MIN_SAMPLES = 2

    # Convert EPSILON from kilometers to radians, as required by scikit-learn's Haversine metric.
    # Earth's mean radius is approximately 6371.0088 km.
    db = DBSCAN(eps=CLUSTERING_EPSILON_KM / 6371.0088, min_samples=CLUSTERING_MIN_SAMPLES, algorithm='ball_tree', metric='haversine')
    labels = db.fit_predict(np.radians(np.array(flat_points)))

    # Tweets per cluster counting
    cluster_counts = Counter(labels)

    # 3. Recognition of "Mixed" Clusters
    cluster_types = {}
    for i, cluster_id in enumerate(labels):
        if cluster_id == -1:
            continue

        if cluster_id not in cluster_types:
            cluster_types[cluster_id] = {'has_forest': False, 'has_urban': False}

        # Conversion to int for safety ('1', 1.0, and 1)
        try:
            f_val = int(float(meta_info[i]['f_pred']))
            u_val = int(float(meta_info[i]['u_pred']))
        except (ValueError, TypeError):
            f_val, u_val = 0, 0

        if f_val == 1:
            cluster_types[cluster_id]['has_forest'] = True
        if u_val == 1:
            cluster_types[cluster_id]['has_urban'] = True

    # 4. Assigning the final 'fire_type'
    for i, meta in enumerate(meta_info):
        cluster_id = labels[i]

        # We store the cluster_id in meta_info to print it in the popup
        meta['cluster_id_debug'] = cluster_id

        try:
            f_val = int(float(meta['f_pred']))
            u_val = int(float(meta['u_pred']))
        except (ValueError, TypeError):
            f_val, u_val = 0, 0

        if cluster_id != -1 and cluster_types[cluster_id]['has_forest'] and cluster_types[cluster_id]['has_urban']:
            meta['fire_type'] = "Mixed Fire (Wildland-Urban Interface)"
        else:
            if f_val == 1 and u_val == 1:
                meta['fire_type'] = "Mixed Fire (Wildland-Urban Interface)"
            elif f_val == 1 and u_val == 0:
                meta['fire_type'] = "Forest Fire"
            elif f_val == 0 and u_val == 1:
                meta['fire_type'] = "Urban Fire"
            else:
                meta['fire_type'] = "Unidentified Type of Fire"

    # --- MAP INITIALIZATION ---
    # Center map on Greece coordinates
    m = folium.Map(location=[MAP_CENTER_LAT, MAP_CENTER_LON], zoom_start=MAP_ZOOM, tiles=None)

    # Add Esri World Imagery (Satellite) as the base layer
    folium.TileLayer(
        tiles='https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}',
        attr='Esri Satellite Imagery',
        name='Esri Satellite'
    ).add_to(m)

    # We also add the simple OSM map
    folium.TileLayer('OpenStreetMap', name='Street View').add_to(m)

    # --- Fire Event Temporal Decay / Fade Out ---

    # Color palette for distinct fire clusters
    colors = ['#FF0000', '#FF8C00', '#FFD700', '#FF4500', '#B22222', '#8B0000', '#E9967A', '#8B4513']

    features = []

    # Fade Out
    opacity_step = INITIAL_OPACITY / FADE_STEPS  # opacity decrease in each step (15%)

    for i, meta in enumerate(meta_info):
        # Convert tweet time to datetime for operations
        try:
            base_time = pd.to_datetime(meta['time'])
        except Exception:
            base_time = pd.to_datetime("2024-01-01 00:00:00") # Security Fallback

        cluster_id = labels[i]
        is_noise = (cluster_id == -1)
        base_color = '#808080' if is_noise else colors[cluster_id % len(colors)]

        if cluster_id == -1:
            size_label = "1"
        else:
            size_label = f"{cluster_counts[cluster_id]}"

        # Creation of multiple "snapshots" (echoes) for the same fire event
        for step in range(FADE_STEPS):
            echo_time = base_time + timedelta(minutes=step * TIME_INTERVAL_MINS)

            # Opacity (brightness) Decrease
            echo_opacity = INITIAL_OPACITY - (step * opacity_step)

            features.append({
                'type': 'Feature',
                'geometry': {'type': 'Point', 'coordinates': [flat_points[i][1], flat_points[i][0]]},
                'properties': {
                    # We set the new display time for the specific echo
                    'time': echo_time.strftime('%Y-%m-%d %H:%M:%S'),
                    # Popup display remains stable, showing the real fire time (meta['time'])
                    'popup': f"<b>Location:</b> <b>{meta['loc_name']}</b> (Cluster: {meta['cluster_id_debug']})<br><b>Timestamp:</b> {meta['time']}<br><b>Type:</b> {meta['fire_type']}<br><b>Tweet:</b> <i>{meta['text']}</i><br><br>This cluster has <b>{size_label}</b> total incident reports<br>",
                    'icon': 'circle',
                    'iconstyle': {
                        'fillColor': base_color,
                        'fillOpacity': echo_opacity,
                        'radius': 8,
                        'stroke': False
                    }
                }
            })

    # --- TIME SLIDER INTEGRATION ---
    # Adds a dynamic time slider to visualize the progression of fire reports
    TimestampedGeoJson(
        {'type': 'FeatureCollection', 'features': features},
        period='PT30M', # 30-minute steps
        duration='PT30M', # Events persist for 30-min hours on map
        time_slider_drag_update=True
    ).add_to(m)

    # Map layer control
    folium.LayerControl(position='topright').add_to(m)

    # Save MAP locally in the Colab environment
    m.save('fire_events_map.html')

    return fire_df

# =============================================================================
# STANDALONE EXECUTION -> EVALUATION MODE
# =============================================================================

if __name__ == "__main__":
    print("--- EVALUATION MODE (Standalone Execution) ---")
    print("STEP 1: Upload the full master_cleaned_dataset (3277 tweets):")
    up_full = files.upload()

    print("\nSTEP 2: Upload the geoparsing Ground Truth EXCEL dataset (147 entries):")
    up_gt = files.upload()

    if up_full and up_gt:

        gt_filename = list(up_gt.keys())[0]
        full_filename = list(up_full.keys())[0]

        print(f"[INFO] Processing Ground Truth file: {gt_filename}")
        print(f"[INFO] Processing Full Dataset file: {full_filename}")

        gt_df = pd.read_excel(io.BytesIO(up_gt[gt_filename]), dtype={'Tweet_ID': str})

        if full_filename.endswith('.csv'):
            full_df = pd.read_csv(io.BytesIO(up_full[full_filename]), dtype={'Tweet_ID': str})
        else:
            full_df = pd.read_excel(io.BytesIO(up_full[full_filename]), dtype={'Tweet_ID': str})

        cols_to_keep = ['Tweet_ID', 'Raw_Text', 'Actual_Toponym', 'Actual_Lat', 'Actual_Lon', 'Notes']
        gt_df = gt_df[ [c for c in cols_to_keep if c in gt_df.columns] ]

        # Convert is_fire to integer (1 or 0)
        if 'is_fire' in full_df.columns:
             full_df['is_fire'] = pd.to_numeric(full_df['is_fire'], errors='coerce').fillna(0).astype(int)
        else:
            full_df['Predicted Label'] = 1
            print("[WARNING] 'is_fire' column not found. Processing all tweets.")

        if 'Light Cleaned Text' not in full_df.columns:
            full_df['Light Cleaned Text'] = full_df.get('Raw_Text', full_df.iloc[:, 1])

        print(f"\n[1/4] Running pipeline on active fire tweets...")

        # Safe date retrieval (returns None if configurated dates are in comment)
        s_date = globals().get('START_DATE')
        e_date = globals().get('END_DATE')

        # start_date and end_date used only for standalone/evaluation execution
        full_results = run_mapping(full_df, start_date=s_date, end_date=e_date)

        if full_results is not None:
            print("\n[2/4] Aligning specific Tweet IDs with Ground Truth...")
            aligned_df = align_geoparsed_results(full_results, gt_df)

            print("\n[3/4] Exporting 'predicted_labels_ner_geoparsing.csv'...")
            aligned_df.to_csv("predicted_labels_ner_geoparsing.csv", index=False)

            print("\n[4/4] Final Metrics:")
            evaluate_geoparsing(aligned_df)
        else:
             print("\n[ERROR] Pipeline returned no results for the specified fire events.")
    else:
        print("\n[ERROR] Both files must be uploaded.")