# -*- coding: utf-8 -*-
"""Part2_Text_Cleaning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zQ0mXV_5gBHJEBJ00t5ETAKNZ8XxBo3k

# Text Cleaning Script for Greek Fire-Related X Posts Dataset

**Description:**

This script performs essential text preprocessing on a dataset of manually labeled tweets.
It creates three distinct variations of cleaned text to accommodate different NLP model requirements:

1.   **Light Cleaning**

  *  Suitable for cased Transformer models and NER applications, where capitalization is a key feature for detecting entities.
  *  Removes noise (URLs, mentions, emojis) but strictly preserves casing, accents, and normalized punctuation.

2.   **Advanced Cleaning**

*   Suitable for uncased Transformer models (like GreekBERT).
*   Takes the light-cleaned text and applies the official GreekBERT preprocessing standards (lowercasing and diacritics removal).


3. **Hard Cleaning**


*   Suitable for traditional baseline models (like SVM with TF-IDF)
*   It performs hashtag segmentation, tokenization, POS tagging, stop word removal and lemmatization. Then it converts text to lowercase and removes punctuation, diacritics, and numbers.


**References:**

*GreekBERT: https://github.com/nlpaueb/greek-bert/blob/master/README.md*

*spaCy (el_core_news_lg): https://spacy.io/models/el*
"""

# --- LIBRARIES & SETUP ---

'''
### The following need to be deleted in the .py file for the simulation
### START
!pip install emoji -q
!pip install spacy -q

# Use of the large (lg) Greek NLP model for optimal word vectoring
# Runs for a few more seconds than the medium-sized (md) one
!python -m spacy download el_core_news_lg -q

### END
'''

import pandas as pd
import re
import io
import html
import emoji
import unicodedata
import spacy

# Load the Greek NLP model globally for speed
nlp = spacy.load("el_core_news_lg")

# --- HELPER FUNCTIONS ---

def light_clean(text):
    """
    Light text cleaning for NER application and cased models.
    Removes irrelevant noise but retains caps and accent.
    """
    if not isinstance(text, str):
        return text

    # Convert HTML entities to standard characters (e.g. '&amp;' becomes '&')
    text = html.unescape(text)

    # Replace all newline, carriage return, and tab characters with a single space
    text = re.sub(r'[\n\r\t]+', ' ', text)

    # Remove all emojis
    text = emoji.replace_emoji(text, replace='')

    # Remove URLs and User Mentions (@username)
    text = re.sub(r'http\S+|www\.\S+', '', text)
    text = re.sub(r'@\w+', '', text)

    # PUNCTUATION NORMALIZATION
    text = re.sub(r'!{2,}', '!', text)         # Multiple !!! become a single !
    text = re.sub(r'\?{2,}', '?', text)        # Multiple ??? become a single ?
    text = re.sub(r';{2,}', ';', text)         # Multiple ;;; become a single ;
    text = re.sub(r'\.{2,}', '...', text)      # 2 dots (..) or more (....) become an ellipsis (...)
    text = re.sub(r'(!\?|\?!)[!?]*', '!?', text) # Mixed combinations like !?! become !?
    text = re.sub(r'(!;|;!)[!;]*', '!;', text)   # Mixed combinations like !;! become !;

    # Clean up of any excess spaces
    return re.sub(r'\s+', ' ', text).strip()

def strip_accents_and_lowercase(s):
    """
    Official preprocessing steps for GreekBERT.
    It removes Greek diacritics (accents) and then converts characters to lowercase.
    """
    if not isinstance(s, str):
        return s

    return ''.join(c for c in unicodedata.normalize('NFD', s)
                   if unicodedata.category(c) != 'Mn').lower()

def segment_hashtags(text):
    """
    Hashtag Segmentation (CamelCase Splitting)
    Converts "#ΦωτιαΣτηνΑθηνα" to " Φωτια Στην Αθηνα"
    """
    if not isinstance(text, str):
        return text

    def split_camel(match):
        word = match.group(0)[1:] # Removal of '#' symbol
        # Inserts a space before any uppercase Greek or Latin letter given that a lowercase is following
        splitted = re.sub(r'(?<=[a-zα-ωάέήίόύώ])([A-ZΑ-ΩΆΈΉΊΌΎΏ])', r' \1', word)
        return splitted

    return re.sub(r'#\w+', split_camel, text)

def spacy_lemmatize(text):
    """
    Applies Lemmatization and Stop Word removal using spaCy library.
    """
    if not isinstance(text, str):
        return text

    doc = nlp(text)
    lemmas = [token.lemma_ for token in doc if not token.is_stop and not token.is_punct and not token.is_space]
    return " ".join(lemmas)

def hard_clean(text):
    """
    Final heavy cleaning for baseline models.
    Removes accents, converts to lowercase, and removes all punctuation and numbers.
    """
    if not isinstance(text, str):
        return text

    # Lowercase and remove accents
    text = strip_accents_and_lowercase(text)
    # Remove all remaining punctuation and numbers
    text = re.sub(r'[^a-zα-ω\s]', ' ', text)
    # Clean up multiple spaces
    return re.sub(r'\s+', ' ', text).strip()

# --- MAIN CLEANING FUNCTION (FOR GENERAL USE) ---

def run_text_cleaning(df):
    """
    Accepts a raw DataFrame, removes duplicates, applies all cleaning stages,
    and returns the cleaned DataFrame.
    """
    print("Starting text cleaning process...")

    # 1. Deduplication (Crucial so it doesn't affect clustering/training)
    initial_size = len(df)
    df = df.drop_duplicates(subset=['Raw Text'], keep='first').copy()
    print(f"Removed {initial_size - len(df)} duplicate tweets.")

    # 2. Apply cleaning tasks
    df['Light Cleaned Text'] = df['Raw Text'].apply(light_clean)
    df['Advanced Cleaned Text'] = df['Light Cleaned Text'].apply(strip_accents_and_lowercase)
    df['Segmented Text'] = df['Light Cleaned Text'].apply(segment_hashtags)
    df['Lemmatized Text'] = df['Segmented Text'].apply(spacy_lemmatize)
    df['Hard Cleaned Text'] = df['Lemmatized Text'].apply(hard_clean)

    # 3. Removal of auxiliary columns
    df = df.drop(columns=['Segmented Text', 'Lemmatized Text'])

    # 4. Delete rows that ended up completely empty after cleaning
    df = df.dropna(subset=['Hard Cleaned Text', 'Advanced Cleaned Text'])
    df = df[df['Hard Cleaned Text'].str.strip() != ""]

    print(f"Cleaning complete! Ready tweets: {len(df)}")
    return df

# --- EXECUTE ONLY WHEN SCRIPT RUNS AUTONOMOUSLY (e.g., for Training) ---

if __name__ == "__main__":
    from google.colab import files

    print("You need to have the manually labeled dataset already downloaded in your PC.")
    print("Please upload it as a CSV or Excel file here:")
    uploaded = files.upload()
    filename = list(uploaded.keys())[0]
    print(f"File '{filename}' was uploaded successfully!\n")

    # Read the file based on its extension
    if filename.endswith('.csv'):
        raw_df = pd.read_csv(io.BytesIO(uploaded[filename]))
    elif filename.endswith(('.xls', '.xlsx')):
        raw_df = pd.read_excel(io.BytesIO(uploaded[filename]))
    else:
        raise ValueError("Unsupported file type. Please upload a .csv or .xlsx file")

    # Call the main cleaning function
    cleaned_df = run_text_cleaning(raw_df)

    # Filter unlabeled data (Applicable ONLY for the training dataset)
    if 'is_fire' in cleaned_df.columns:
        cleaned_df = cleaned_df.dropna(subset=['is_fire'])
        print(f"After dropping unlabeled rows, {len(cleaned_df)} tweets remain.")

        # Class Imbalance Check
        print("\n--- Class Imbalance Check ---")
        label_counts = cleaned_df['is_fire'].value_counts()
        total_tweets = len(cleaned_df)

        for label, count in label_counts.items():
            percentage = (count / total_tweets) * 100
            print(f"Label {label}: {count} tweets ({percentage:.2f}%)")
        print("-----------------------------\n")

    # FINAL EXPORT
    cleaned_df.to_csv('master_cleaned_dataset.csv', index=False)

    print("\n==============================================================")
    print("PREPROCESSING COMPLETE!")
    print("The dataset has been saved as 'master_cleaned_dataset.csv'.")
    print("Available cleaned text formats:")
    print(" 1. 'Light Cleaned Text'    -> For NER")
    print(" 2. 'Advanced Cleaned Text' -> For GreekBERT")
    print(" 3. 'Hard Cleaned Text'     -> For Baseline Models (like SVM)")
    print("================================================================")